version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: legacy_frontend
    restart: always
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
